apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
{{ include "api-deploy.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "api-deploy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
